# Generated by Django 5.2.4 on 2025-08-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='question_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('quizid', models.CharField(max_length=100)),
                ('question', models.TextField()),
                ('op1', models.CharField(max_length=200)),
                ('op2', models.CharField(max_length=200)),
                ('op3', models.CharField(max_length=200)),
                ('op4', models.CharField(max_length=200)),
                ('correct_option', models.CharField(choices=[('op1', 'option 1'), ('op2', 'option 2'), ('op3', 'option 3'), ('op4', 'option 4')], max_length=100)),
            ],
        ),
    ]
