# Generated by Django 5.2.4 on 2025-08-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_list',
            name='questionid',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
