# Generated by Django 5.2.4 on 2025-08-09 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_question_list_questionid'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_list',
            name='mark',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
