# Generated by Django 5.2.4 on 2025-08-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='answer_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempted_by', models.CharField(max_length=100)),
                ('quizid', models.CharField(max_length=100)),
                ('questionid', models.CharField(max_length=100)),
                ('chosen_option', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=100)),
            ],
        ),
    ]
