# Generated by Django 5.2.4 on 2025-08-09 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='scorecard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempted_by', models.CharField(max_length=100)),
                ('quizid', models.CharField(max_length=100)),
                ('correct', models.IntegerField()),
                ('incorrect', models.IntegerField()),
                ('total', models.IntegerField()),
                ('score', models.IntegerField()),
            ],
        ),
    ]
