# Generated by Django 5.2.4 on 2025-08-10 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0002_scorecard'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer_list',
            name='mark',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
